name: release

on: 
  release:
    types:
      - published

jobs:
  sync-to-starters:
    runs-on: ubuntu-latest
    name: Sync to Starters
    # permissions:
    #   contents: write
    steps:
    - name: Checkout Eureka
      uses: actions/checkout@v2
      with:
        path: 'eureka'
    - name: Checkout Starters
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: 'wangchucheng/hugo-eureka-starters-test'
        path: 'starters'
    - name: Delete Old Folders
      run: rm -rf starters/config starters/content 
    - name: Copy New Folders
      run: | 
        cp -r eureka/exampleSite/config/. starters/config
        cp -r eureka/exampleSite/content/. starters/content
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Commit
      run: | 
        cd starters
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add . && git commit -m "chore: upgrade to ${GITHUB_REF}"
        git config --unset-all http.https://github.com/.extraheader # https://stackoverflow.com/a/69979203
    - name: Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        directory: starters
        repository: wangchucheng/hugo-eureka-starters-test
        branch: monolingual
    - name: Release Starters
      uses: softprops/action-gh-release@v1
      with:
        repository: wangchucheng/hugo-eureka-starters-test
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
    - name: Update Hugo Modules
      run: |
        cd starters
        hugo mod get -u
    